In [19]:
from dotenv import load_dotenv
import os
import requests
import json
import pandas as pd
import quandl
import matplotlib

%matplotlib inline

In [2]:
load_dotenv()

True

In [3]:
quandl.ApiConfig.api_key = os.getenv('QUANDL_API_KEY')

In [43]:
data = quandl.get_table('ZILLOW/DATA', indicator_id='Z1BR', region_id='268020')
data

     indicator_id region_id       date      value
None
0            Z1BR    268020 2020-12-31  1209880.0
1            Z1BR    268020 2020-11-30  1221959.0
2            Z1BR    268020 2020-10-31  1232359.0
3            Z1BR    268020 2020-09-30  1249561.0
4            Z1BR    268020 2020-08-31  1270730.0
5            Z1BR    268020 2020-07-31  1268802.0
6            Z1BR    268020 2020-06-30  1289970.0
7            Z1BR    268020 2020-05-31  1336873.0
8            Z1BR    268020 2020-04-30  1356495.0
9            Z1BR    268020 2020-03-31  1362229.0
10           Z1BR    268020 2020-02-29  1360273.0
11           Z1BR    268020 2020-01-31  1346709.0
12           Z1BR    268020 2019-12-31  1331776.0
13           Z1BR    268020 2019-11-30  1318294.0
14           Z1BR    268020 2019-10-31  1312200.0
15           Z1BR    268020 2019-09-30  1310071.0
16           Z1BR    268020 2019-08-31  1315358.0
17           Z1BR    268020 2019-07-31  1319143.0
18           Z1BR    268020 2019-06-30  1304018.0
19           Z1BR    268020 2019-05-31  1285372.0
20           Z1BR    268020 2019-04-30  1266454.0
21           Z1BR    268020 2019-03-31  1269328.0
22           Z1BR    268020 2019-02-28  1280494.0
23           Z1BR    268020 2019-01-31  1297664.0
24           Z1BR    268020 2018-12-31  1310438.0
25           Z1BR    268020 2018-11-30  1320497.0
26           Z1BR    268020 2018-10-31  1318410.0
27           Z1BR    268020 2018-09-30  1311831.0
28           Z1BR    268020 2018-08-31  1286386.0
29           Z1BR    268020 2018-07-31  1253046.0
...           ...       ...        ...        ...
270          Z1BR    268020 1998-06-30   285815.0
271          Z1BR    268020 1998-05-31   282533.0
272          Z1BR    268020 1998-04-30   278977.0
273          Z1BR    268020 1998-03-31   276930.0
274          Z1BR    268020 1998-02-28   274088.0
275          Z1BR    268020 1998-01-31   271666.0
276          Z1BR    268020 1997-12-31   266571.0
277          Z1BR    268020 1997-11-30   261595.0
278          Z1BR    268020 1997-10-31   255870.0
279          Z1BR    268020 1997-09-30   252325.0
280          Z1BR    268020 1997-08-31   248634.0
281          Z1BR    268020 1997-07-31   245729.0
282          Z1BR    268020 1997-06-30   242289.0
283          Z1BR    268020 1997-05-31   238280.0
284          Z1BR    268020 1997-04-30   234556.0
285          Z1BR    268020 1997-03-31   231065.0
286          Z1BR    268020 1997-02-28   227552.0
287          Z1BR    268020 1997-01-31   223528.0
288          Z1BR    268020 1996-12-31   222122.0
289          Z1BR    268020 1996-11-30   221185.0
290          Z1BR    268020 1996-10-31   222190.0
291          Z1BR    268020 1996-09-30   221753.0
292          Z1BR    268020 1996-08-31   221452.0
293          Z1BR    268020 1996-07-31   220516.0
294          Z1BR    268020 1996-06-30   220636.0
295          Z1BR    268020 1996-05-31   221082.0
296          Z1BR    268020 1996-04-30   221973.0
297          Z1BR    268020 1996-03-31   222905.0
298          Z1BR    268020 1996-02-29   223627.0
299          Z1BR    268020 1996-01-31   224778.0

[300 rows x 4 columns]